### ISSUE TITLE
Re-evaluation of unknown symbol does not work

### ISSUE THREAD

**Issue by mincequi** [Blake-Madden/tinyexpr-plusplus#10]
Hi @Blake-Madden,

I once requested a change from your lib, which you directly implemented. Thanks for that.
Unfortunately, I got an issue with that or I do not understand its usage.
Consider these lines of code:

```
    std::string str("id.temperature < 51");
    te_parser parser;
    parser.set_unknown_symbol_resolver([](std::string_view symbol) {
        static double temperature = 49.0;
        return temperature += 1.0;
    }, false); // although I set false here, the evaluation callback is not called a second time
    assert(parser.compile(str));
    assert(parser.evaluate() == 1.0);
    assert(parser.evaluate() == 0.0);
```

So, the unknown symbol resolver should actually re-evaluate the new value. However, this is not happening.
Could you help me here, please?

Thanks a lot!

Best regards
Manuel

**Comment by Blake-Madden** [comment]
I'll check it out...

**Comment by mincequi** [comment]
Thanks already.

Another thing to consider: the current implementation of `te_parser::set_unknown_symbol_resolver` accepts only plain old function pointers. So, I cannot capture any variables with the lambda and if I want to pass in a variable, it has to be static.

Currently:
```
    te_parser parser;
    parser.set_unknown_symbol_resolver([](std::string_view symbol) {
        static double temperature = 49.0;
        return temperature += 1.0;
    });
```
vs.
```
    te_parser parser;
    double temperature = 49.0;
    parser.set_unknown_symbol_resolver([&](std::string_view symbol) {
        return temperature += 1.0;
    });
```

**Comment by Blake-Madden** [comment]
I'll be checking in a fix for `evaluate(expression)` being called after `compile(expression)` not causing the USR to be called again.  For `evaluate()`, I'll have to say that it is by design to not call the USR again.  When an expression is compiled, the variables in it get optimized out (replaced with their value), so calling `evaluate()` will not see those variables in the expression again since they were optimized out. The solution would need to be call `evaluate(expression)` instead with the original expression if you want to force the USR to be called again.

**Comment by Blake-Madden** [comment]
Lambda with capture is fixed for USR now also, thanks for pointing that out.

**Comment by mincequi** [comment]
Good news. Thanks again 👍
