### ISSUE TITLE
Alternative syntax for boolean expressions?

### ISSUE THREAD

**Issue by mincequi** [Blake-Madden/tinyexpr-plusplus#11]
Hi there,
I don't know, whether this could be done easily, but at best, I would like to have a more "natural" syntax for boolean expressions:

Imagine:
`id.temperature < 53 and grid_power < -1400`
instead of
`and(id.temperature < 53, grid_power < -1400)`

Actually, exprtk provides the first syntax.

What do you think?

**Comment by Blake-Madden** [comment]
There is `&` and `|` operators, so you can do this:

`id.temperature < 53 & grid_power < -1400`

I agree that's not as elegant, but it does allow the needed syntax.

The reason I have `AND` and `OR` as functions is because that's how they are in Excel. I try to emulate spreadsheet formulas' syntax as closely as I can (for better or for worse).
