### ISSUE TITLE
Support all 64-bit representable values

### ISSUE THREAD

**Issue by VelocityRa** [Blake-Madden/tinyexpr-plusplus#13]
I can see that values are stored as `double`, so presumably it [can't](https://stackoverflow.com/a/3793950) be used for all values representable by a `uint64_t`.

This would be needed for example to be able to use this library for calculating memory addresses (my particular use case is a debugging-related tool).

**Comment by Blake-Madden** [comment]
You can change the storage type to `float` using a `#define`; I suppose I could add another `#define` for `uint64_t`. All the calculations will lose their precision and some functions may not be available, but I think that might be OK for your needs. I'll explore that this week.

I would try `long double`, but its range is compiler specific and may not always accommodate an `uint64_t` value.

**Comment by Blake-Madden** [comment]
Let me know of any example expressions you would need to parse. I can use those as test cases if I am able to add this option.

**Comment by VelocityRa** [comment]
Ah I see, thank you!

As for examples, the basic ones you always need in use-cases such as mine (memory address expressions) in order from most to least important in my opinion, are:
- **Memory dereferencing**: Syntax like `[rbp+100]` would call a function `uint64_t dereference(uint64_t addr) ` or similar (after resolving the `rbp` constant and performing the addition) to perform the deref (like in ie. [x64dbg](https://help.x64dbg.com/en/latest/introduction/Values.html#memory-locations))
- **Treating all values as hex** (like ie. [x64dbg](https://help.x64dbg.com/en/latest/introduction/Values.html#numbers))
  - Optionally support prepending with `0x` or appending with `h`, as is common for hex values
  - Optionally support decimal values (perhaps by prepending with `.`)
- **Bitwise operations**. and (`&`), or (`|`), shift (`<<`, `>>`) and perhaps not (`~`), xor (`^`) and rotate (`<<<`, `>>>`), like ie. [x64dbg](https://help.x64dbg.com/en/latest/introduction/Expressions.html#operators)

**Comment by Blake-Madden** [comment]
Unfortunately, I have to stay with floating-point types because I rely on a value of NaN to signal a failure state. So, the best I could do is add an option to use `long double`. From my experiments, 64-bit ICC, GCC, and CLang all use a `long double` that can hold `uint64_t` values. But for MSVC 64-bit, it can't (I suspect `long double` is the same as `double` there).

I'll go ahead and work on adding an option to switch to `long double`; that may be of use to you if you are using something other than MSCV.

I'll check out the other features also. I do support `<<` and `>>` currently, but I didn't document them yet.

**Comment by Blake-Madden** [comment]
I've created separate issues for Hex values and the `~` operator; otherwise, I've done what I can for this.  If you define `TE_LONG_DOUBLE`, that will support `uint64_t` values with clang and GCC, but MSVC will be limited to 53-bit integer values unfortunately. I added a `supports_64()` constexpr and `SUPPORTS64()` formula to check for what's supported.

Defining `TE_BRACKETS_AS_PARENS` will allow for `[rbp+100]` syntax.

Defining `TE_BITWISE_OPERATORS` will make `^`, `|`, and `&` work as you would expect.  I added the shift and rotation operators too.

**Comment by VelocityRa** [comment]
> Defining `TE_BRACKETS_AS_PARENS` will allow for `[rbp+100]` syntax.

Took a quick look at the code and sure if that's usable for the purpose of debugger-adjacent tooling as-is, the library user would also need to handle the actual dereferencing - you need to call a user specified callback. It's not enough to treat it the same way as parentheses.

Anyway Windows with MSVC is my main platform so I can't use this - also looked around and it's not even possible as a compiler switch unfortunately. Perhaps clang-cl would work but probably not worth switching my entire project over.

Thank you, I appreciate you looking into it regardless - I'll figure something out :)

**Comment by Blake-Madden** [comment]
Yeah, sorry this couldn't work out. The program at least has some new nice functionality, so thanks for the feedback.

Interestingly, I suspect Excel does the same thing that I am doing, where I am storing doubles and converting them to ints for bitwise operations. The Excel function `BITLSHIFT` curiously limits the shift amount to 53, not 64. They make it 53 since that is the number of digits that either `double` or `long double` will handle with MSVC.
